addresses:
    constraints:
        not_null:
            - address_id
        unique:
            - address_id

customers:
    constraints:
        not_null:
            - customer_id
        unique:
            - customer_id

order_items:
    constraints:
        not_null:
            - order_item_id
        unique:
            - order_item_id
        relationships:
            - {from: order_id, to: ref('orders'), field: order_id}
            - {from: product_id, to: ref('products'), field: product_id}

orders_xf:
    constraints:
        not_null:
            - email
            - order_id
            - created_at
            - order_year
            - order_month
            - order_day_of_month
            - is_completed
            - lifetime_placed_orders
            - lifetime_completed_orders
            - lifetime_revenue
            - customer_type
            - customer_first_30_day_completed_orders
            - customer_first_60_day_completed_orders
            - customer_first_90_day_completed_orders
        unique:
            - order_id
        relationships:
            - {from: email, to: ref('customers'), field: email}

products:
    constraints:
        not_null:
            - product_id
        unique:
            - product_id
