version: 2
models:
- name: ADDRESSES
  columns:
  - name: address_id
    tests:
    - not_null
    - unique

- name: CUSTOMERS
  columns:
  - name: customer_id
    tests:
    - not_null
    - unique

- name: ORDERS_CALCULATIONS
  columns:
  - name: order_id
    tests:
    - not_null
    - unique

- name: PRODUCTS
  columns:
  - name: product_id
    tests:
    - not_null
    - unique

- name: ORDERS_XF
  columns:
  - name: order_id
    tests:
    - not_null
    - unique

- name: ORDER_ITEMS
  columns:
  - name: order_item_id
    tests:
    - not_null
    - unique
    name: email
    tests:
    - not_null
    
    name: order_id
    tests:
    - not_null
    
    name: created_at
    tests:
    - not_null
    
    name: created_date
    tests:
    - not_null
    
    name: is_completed
    tests:
    - not_null
    
    name: lifetime_placed_orders
    tests:
    - not_null
    
    name: lifetime_completed_orders
    tests:
    - not_null
    
    name: lifetime_revenue
    tests:
    - not_null
    
    name: customer_type
    tests:
    - not_null
    
    name: customer_first_30_day_completed_orders
    tests:
    - not_null
    
    name: customer_first_60_day_completed_orders
    tests:
    - not_null
    
    name: customer_first_90_day_completed_orders
    tests:
    - not_null
