version: 2

models:
    
- name: addresses
  columns:
  - name: address_id
    tests:
    - not_null
    - unique
    
- name: customers
  description: '{{doc("ecommerce_customers")}}'
  columns:
  - name: customer_id
    tests:
    - not_null
    - unique
    
- name: order_items
  columns:
  - name: order_id
    tests:
    - relationships:
        field: order_id
        to: ref('orders_xf')
  - name: order_item_id
    tests:
    - not_null
    - unique
    
- name: orders_calculations
  description: '{{doc("order_calculations")}}'
  columns:
  - name: order_id
    tests:
    - not_null
    - unique

- name: orders_xf
  description: '{{doc("order_final")}}'
  columns:
  - name: created_at
    tests:
    - not_null
  - name: customer_id
    tests:
    - not_null
  - name: email
    tests:
    - not_null
  - name: order_id
    tests:
    - not_null
    - unique
    
- name: products
  columns:
  - name: product_id
    tests:
    - not_null
    - unique
