version: 2

models:
    
- name: addresses
  columns:
  - name: address_id
    tests:
    - not_null
    - unique
    
- name: customers
  columns:
  - name: customer_id
    tests:
    - not_null
    - unique
    
- name: order_items
  columns:
  - name: order_id
    tests:
    - relationships:
        field: order_id
        to: ref('orders')
  - name: order_item_id
    tests:
    - not_null
    - unique
    
- name: orders_xf
  columns:
  - name: created_at
    tests:
    - not_null
  - name: customer_id
    tests:
    - relationships:
        field: customer_id
        to: ref('customers')
  - name: email
    tests:
    - not_null
  - name: order_id
    tests:
    - not_null
    - unique
    
- name: products
  columns:
  - name: product_id
    tests:
    - not_null
    - unique
